language: c
sudo: true
before_install:
  - export PATH="/tmp/bin:$HOME/bin:$PATH"
  - echo 'before install' && pwd && ls
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_17461f6c229b_key -iv $encrypted_17461f6c229b_iv
    -in 4travis.enc -out ~/.ssh/4travis -d
  - chmod 600 ~/.ssh/4travis
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/4travis
  - cp ssh_config ~/.ssh/config
  - git config --global user.email "cxumol@163.com"
  - git config --global user.name "cxumol"
install:
  - mkdir -p /tmp/bin && cd /tmp/bin
  - wget https://github.com/whudoc/statics/raw/master/qrsync.tar.gz
  - tar xfz qrsync.tar.gz
  - chmod +x qrsync
  - wget https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-1-amd64.deb
  - sudo dpkg -i pandoc*.deb
script:
  - cd ~/build/cxumol/timeline-notes;
  - make clone
  - make include all sitemap
  - cat meta/conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > conf.json
  - qrsync conf.json
  - cd publish
  - git init; git add -A; git commit -m "publish2coding:coding-pages, lazy me @ `date`"
  - git remote add origin2 git@git.coding.net:cxumol/note.timeline.git
  - git push -u origin2 HEAD:coding-pages --force
  - cd ..; rm -Rf publish; git reset --hard HEAD;
  - rm -Rf .git
  - git init; git add -A; git commit -m "backup2coding:master, lazy me @ `date`"
  - git remote add origin2 git@git.coding.net:cxumol/note.timeline.git
  - git push -u origin2 HEAD:master --force
